name: RDM Solution CI/CD

on:
  push:
    branches:
      - dev
      - stage
      - prod

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install AWS CLI
        run: |
          sudo apt-get update && \
          sudo apt-get install -y awscli
      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install CDK and Dependencies
        run: |
          python -m pip install --upgrade pip && \
          pip install aws-cdk.aws-s3 aws-cdk.aws-lambda aws-cdk.aws-iam
      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt
      - name: Deploy dev CDK environment
        run: cdk deploy --context env=dev
      - name: Sync local files to S3
        run: |
          aws s3 sync s3://scheme-dev-ref-data s3://scheme-ref-dev-data-copy
        
  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy stage environment
        run: |
          cd cdk && \
          cdk deploy --context env=stage
      - name: Sync local files to S3
        run: |
          aws s3 sync local_dir s3://my-bucket/stage
        
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy prod environment
        run: |
          cd cdk && \
          cdk deploy --context env=prod
      - name: Sync local files to S3
        run: |
          aws s3 sync local_dir s3://my-bucket/prod