name: RDM Solution CI/CD

on:
  push:
    branches:
      - dev
      - stage
      - prod

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update && \
          sudo apt-get install -y awscli
      - name: Deploy dev environment
        run: |
          cdk deploy --context env=dev
      - name: Sync local files to S3
        run: |
          aws s3 sync s3://scheme-dev-ref-data s3://scheme-ref-dev-data-copy
        
  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy stage environment
        run: |
          cd cdk && \
          cdk deploy --context env=stage
      - name: Sync local files to S3
        run: |
          aws s3 sync local_dir s3://my-bucket/stage
        
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy prod environment
        run: |
          cd cdk && \
          cdk deploy --context env=prod
      - name: Sync local files to S3
        run: |
          aws s3 sync local_dir s3://my-bucket/prod